version: '3.0'
services:
  bunchopage:
    image: bunchopage
    container_name: bunchopage
    build:
      context: .
      dockerfile: ./app/Dockerfile
    environment:
      - WATCHPACK_POLLING=true
    ports:
      - "$CONTAINER_PORT:$CONTAINER_PORT"
    volumes:
      - "./app:/app"
      - nodemodules:/app/bunchoPage/node_modules
    tty: true
  bunchodb:
    container_name: bunchodb
    image: postgres:10.7-alpine
    restart: always
    volumes:
      - ./postgres/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    ports:
      - "$POSTGRES_PORT:$POSTGRES_PORT"
volumes:
  nodemodules:
